Add branch to merge_group on action (#77)
Summery: Adds master branch to merge-group.
Type: Feature
Test Plan: Actions succeed
Jira: RIALTO-362

diff --git a/.github/workflows/commit_message_format.yml b/.github/workflows/commit_message_format.yml
--- a/.github/workflows/commit_message_format.yml
+++ b/.github/workflows/commit_message_format.yml
@@ -20,8 +20,9 @@ name: commit-message-format
 
 # Controls when the workflow will run
 on:
-  # Triggers the workflow on a merge queue
-  merge_group:
+  # Triggers the workflow on pull request to master branch
+  pull_request:
+    branches: [ "master", "rdkcentral:master" ]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -34,41 +35,60 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Get PR Commits
-        id: 'get-pr-commits'
-        uses: tim-actions/get-pr-commits@master
+      # Check PR description for 'Summery:' field.
+      - name: Match 'Summery:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: summery-match
+        if: failure() || success()
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Summery:\s*[\s\S]*?'
+          flags: gm
 
-      - name: Check required Summery field
-        if: ${{ success() || failure() }}
-        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
+      - name: Check 'Summery:' 
+        if: (failure() || success()) && (steps.summery-match.outputs.match == '')
+        run: exit 1
+  
+      # Check PR description for 'Type: Feature|Fix|Cleanup' field.
+      - name: Match 'Type:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: type-match
+        if: failure() || success()
         with:
-          commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '\nSummery:\s*[\s\S]*?'
-          error: "Require a 'Summery:' field"
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Type:\s*Feature|Fix|Cleanup'
+
+      - name: Check 'Type:' 
+        if: (failure() || success()) && (steps.type-match.outputs.match == '')
+        run: exit 1
+        
+      # Check PR description for 'Test Plan:' field.
+      - name: Match 'Test Plan:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: test-plan-match
+        if: failure() || success()
+        with:
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Test Plan:\s*[\s\S]*?'
+
+      - name: Check 'Test Plan:' 
+        if: (failure() || success()) && (steps.test-plan-match.outputs.match == '')
+        run: exit 1
+
+      # Check PR description for 'Jira:' field.
+      - name: Match 'Jira:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: jira-match
+        if: failure() || success()
+        with:
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Jira:\s*[\s\S]*?'
+
+      - name: Check 'Jira:' 
+        if: (failure() || success()) && (steps.jira-match.outputs.match == '')
+        run: exit 1
       
-      - name: Check required Type field
-        if: ${{ success() || failure() }}
-        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
-        with:
-          commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '\nType:\s*Feature|Fix|Cleanup'
-          error: "Require a 'Type: Feature/Fix/Cleanup' field"
-
-      - name: Check required Test Plan field
-        if: ${{ success() || failure() }}
-        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
-        with:
-          commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '\nTest Plan:\s*[\s\S]*?'
-          error: "Require a 'Test Plan:' field"
-
-      - name: Check required Jira field
-        if: ${{ success() || failure() }}
-        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
-        with:
-          commits: ${{ steps.get-pr-commits.outputs.commits }}
-          pattern: '\nJira:\s*[\s\S]*?'
-          error: "Require a 'Jira:' field, if no jira put 'Jira: NO-JIRA'"
-
+      # Print description.
+      - name: Log string on failure
+        if: failure()
+        run: echo ${{ github.event.pull_request.body }}
