Add other fields

diff --git a/.github/workflows/commit_message_format.yml b/.github/workflows/commit_message_format.yml
--- a/.github/workflows/commit_message_format.yml
+++ b/.github/workflows/commit_message_format.yml
@@ -35,17 +35,63 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Search for 'Summery:' 
+      # Check PR description for 'Summery:' field.
+      - name: Match 'Summery:' 
         uses: actions-ecosystem/action-regex-match@v2
         id: summery-match
         if: failure() || success()
         with:
-          text: ${{ github.event.pull_request.body }}
-          regex: 'Sumery:\s*[\s\S]*?'
+          text: \n${{ github.event.pull_request.body }}
+          regex: '\nSummery:\s*[\s\S]*?'
           flags: gm
-
-      - run: echo ${{ github.event.pull_request.body }}
 
       - name: Check 'Summery:' 
         if: (failure() || success()) && (steps.summery-match.outputs.match == '')
         run: exit 1
+  
+      # Check PR description for 'Type: Feature|Fix|Cleanup' field.
+      - name: Match 'Type:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: type-match
+        if: failure() || success()
+        with:
+          text: \n${{ github.event.pull_request.body }}
+          regex: '\nType:\s*Feature|Fix|Cleanup'
+          flags: gm
+
+      - name: Check 'Type:' 
+        if: (failure() || success()) && (steps.type-match.outputs.match == '')
+        run: exit 1
+        
+      # Check PR description for 'Test Plan:' field.
+      - name: Match 'Test Plan:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: test-plan-match
+        if: failure() || success()
+        with:
+          text: \n${{ github.event.pull_request.body }}
+          regex: '\nTest Plan:\s*[\s\S]*?'
+          flags: gm
+
+      - name: Check 'Test Plan:' 
+        if: (failure() || success()) && (steps.test-plan-match.outputs.match == '')
+        run: exit 1
+
+      # Check PR description for 'Jira:' field.
+      - name: Match 'Jira:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: jira-match
+        if: failure() || success()
+        with:
+          text: \n${{ github.event.pull_request.body }}
+          regex: '\nJira:\s*[\s\S]*?'
+          flags: gm
+
+      - name: Check 'Jira:' 
+        if: (failure() || success()) && (steps.jira-match.outputs.match == '')
+        run: exit 1
+      
+      # Print description.
+      - name: Log string on failure
+        if: failure()
+        run: echo \n${{ github.event.pull_request.body }}
